---
# tasks file for ansibleMaster
- name: add repository
  apt_repository:
    repo: ppa:ansible/ansible
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'
- name: install tools
  apt:
    name: ansible
    state: latest
- name: install pip
  easy_install:
    name: pip
    state: latest
- name: install pywinrm
  pip:
    name: pywinrm
